version: "3.7"
services:
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: ./notebook.Dockerfile
    ports:
      - 80:8888
      - 6006:6006
    volumes:
      - ./src:/home/jovyan/src
      - ./notebooks:/home/jovyan/notebooks
      - ./data:/home/jovyan/data
      - ./logs:/home/jovyan/logs
    networks: 
      - intrinio_sync_default

networks:
  intrinio_sync_default:
    external: true